-- Add fields for game upload feature
ALTER TABLE games ADD COLUMN IF NOT EXISTS division TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS client TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS season TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS area TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS half_duration INTEGER;
ALTER TABLE games ADD COLUMN IF NOT EXISTS halftime_duration INTEGER;
ALTER TABLE games ADD COLUMN IF NOT EXISTS comments TEXT;
